export const HEADER_TYPE = "HEADER_TYPE";
export const FETCH_PRODUCTS_START   = 'FETCH_PRODUCTS_START';
export const FETCH_PRODUCTS_SUCCESS = 'FETCH_PRODUCTS_SUCCESS';
export const FETCH_PRODUCTS_FAILURE = 'FETCH_PRODUCTS_FAILURE';
export const SELECT_ACTION = 'SELECT_ACTION';
export const COMPLETE_SELECTED = 'COMPLETE_SELECTED';
export const MODIFY_COUNT = 'MODIFY_COUNT';